version: '3.8'

services:
    llm-social-filter:
        image: ghcr.io/levabala/llm-social-filter:latest
        container_name: llm-social-filter
        restart: unless-stopped
        environment:
            - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TWITTERAPIIO_KEY=${TWITTERAPIIO_KEY}
            - ADMIN_USERNAME=${ADMIN_USERNAME}
            - MAX_FOLLOWINGS=${MAX_FOLLOWINGS}
            - TWITTERAPIIO_FILTER_RULE_ID=${TWITTERAPIIO_FILTER_RULE_ID}
            - USERNAME_TO_FOLLOW=${USERNAME_TO_FOLLOW}
            - DB_ROOT_DIR=${DB_ROOT_DIR}
        volumes:
            - llm-social-filter-data:/app/data
        ports:
            - "3000:3000"

volumes:
    llm-social-filter-data:
